### ISSUE TITLE
HTTP error 500 after deployment to live server

### ISSUE THREAD

**Issue by lottaar** [749/modx_facebook_feed#13]
After deployment from localhost to my live host the Facebook Integration module crashes my site and gives a HTTP error 500. Nothing in the MODX error logs but in the server logs I get this:

```
[Thu Apr 06 10:31:11 2017] [warn] [client xx.xx.xx.xxx] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function ereg_replace() in /var/www/vhosts/domain.se/demo.domain.se/core/components/facebook_feed/model/fb_feed/feed.class.php:352
[Thu Apr 06 10:31:11 2017] [warn] [client xx.xx.xx.xxx] mod_fcgid: stderr: Stack trace:
[Thu Apr 06 10:31:11 2017] [warn] [client xx.xx.xx.xxx] mod_fcgid: stderr: #0 /var/www/vhosts/domain.se/demo.domain.se/core/components/facebook_feed/model/fb_feed/feed.class.php(273): Feed->txt2link('#MODX Revolutio...', Array)
[Thu Apr 06 10:31:11 2017] [warn] [client xx.xx.xx.xxx] mod_fcgid: stderr: #1 /var/www/vhosts/domain.se/demo.domain.se/core/cache/includes/elements/modsnippet/82.include.cache.php(35): Feed->runFeed(Array)
[Thu Apr 06 10:31:11 2017] [warn] [client xx.xx.xx.xxx] mod_fcgid: stderr: #2 /var/www/vhosts/domain.se/demo.domain.se/core/model/modx/modscript.class.php(70): include('/var/www/vhosts...')
[Thu Apr 06 10:31:11 2017] [warn] [client xx.xx.xx.xxx] mod_fcgid: stderr: #3 /var/www/vhosts/domain.se/demo.domain.se/core/model/modx/modparser.class.php(521): modScript->process()
[Thu Apr 06 10:31:11 2017] [warn] [client xx.xx.xx.xxx] mod_fcgid: stderr: #4 /var/www/vhosts/domain.se/demo.domain.se/core/model/modx/modparser.class.php(250): modParser->processTag(Array, true)
[Thu Apr 06 10:31:11 2017] [warn] [client xx.xx.xx.xxx] mod_fcgid: stderr: #5 /var/www/vhosts/domain.se/demo.domain.se/core/model/modx/modresponse.class.php(69): modParser->processElementTags('', '<!DOCTYPE html>...', true, false, '[[', ']]', Array, 9) in /var/www/vhosts/domain.se/demo.domain.se/core/components/facebook_feed/model/fb_feed/feed.class.php on line 352
```

Facebook Integration 0.2.8-beta
MODX 2.5.6
PHP 7 FastCGI

**Comment by 749** [comment]
I am currently still using a the ereg_replace function which has been removed in php version7.
I will fix it this evening.

**Comment by lottaar** [comment]
Great, thanks! For information, I tested with PHP 5.3.3 as well but got error 500 then too and another error in the log. But that was perhaps the opposite problem, with the PHP version being too old :)

`mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '[', expecting ')'`

**Comment by 749** [comment]
I am using Facebooks api, which needs at least php version 5.4, any older version will definitly not work

**Comment by lottaar** [comment]
I see. You've done a great job and thank you for fixing any issues to quickly! It's so much nicer to be able to design your own feed rather than using Facebook's own horrendous feed. Well done!

**Comment by 749** [comment]
Thank you very much, it's reponses like these that keep me going 👍

**Comment by 749** [comment]
The fixed version should now be available through the package management.
